### ISSUE TITLE
Japanese character support missing

### ISSUE THREAD

**Issue by atimeofday** [flathub/com.vivaldi.Vivaldi#21]
Vivaldi flatpak is unable to display Japanese text. I am unsure if this is a system issue, but if it is possible to bundle language support in the flatpak if it is not found, that may be beneficial.

**Comment by ruario** [comment]
Could you test something for me. Using flatseal provide read only access to "/usr/share/fonts" and "xdg-data/fonts" and see if this resolves your issue.

**Comment by ruario** [comment]
Is it better now after the latest update?

**Comment by atimeofday** [comment]
(Before today, read only access to those two directories did not fix the issue.)

As of today, on version 6.5.3206.57, with *or without* access to those two directories, it appears to be fixed. Thanks!
