### ISSUE TITLE
Making flags persistent

### ISSUE THREAD

**Issue by Kagukara** [flathub/com.vivaldi.Vivaldi#3]
In archlinux you can have a `vivaldi-stable.conf` file placed in `$HOME/.config/`, how would I go about doing the equivalent for the flatpak version of vivaldi?

For chromium I've seen people say you place a file named `chromium-flags.conf` in `~/.var/app/org.chromium.Chromium/config/chromium-flags.conf`.

**Comment by evenreven** [comment]
I just tried adding `~/.var/app/com.vivaldi.Vivaldi/config/vivaldi-flags.conf`, and it magically works (just like chromium-flags.conf and edge-flags.conf works for Chromium and Edge, respectively).

I can tell it works because I'm using fractional scaling and I need this setting to avoid blur:

```
--ozone-platform=wayland
--enable-features=UseOzonePlatform
```
