### ISSUE TITLE
Vivaldi is actually licensed under a BSD 3-Clause License, it is not proprietary.

### ISSUE THREAD

**Issue by RageGamerBoi** [flathub/com.vivaldi.Vivaldi#62]
Vivaldi is actually licensed under a BSD 3-Clause License, it is not proprietary.
See https://vivaldi.com/source/ for details.

**Comment by ruario** [comment]
That is the license for the C++ parts including all the changes to Chromium. The UI, written in various web technologies is not open source. Thus Vivaldi browser is part open-source, part closed-source. Read this for more:

https://vivaldi.com/blog/vivaldi-browser-open-source/

P.S. I am a Vivaldi employee, so I know the situation with the license as well as anybody.
