### ISSUE TITLE
App has 'Unverified' tag on Flathub, what makes it unavailable on Linux Mint

### ISSUE THREAD

**Issue by Ser-Bul** [flathub/com.vivaldi.Vivaldi#82]
Having 'Unverified' tag means it's hidden from Software Manager search results on Linux Mint (https://www.phoronix.com/news/Linux-Mint-Unverified-Flatpaks)
@ruario, please perform the verification https://docs.flathub.org/docs/for-app-authors/verification

**Comment by ruario** [comment]
We are not making it official yet. This has been discussed elsewhere

https://social.vivaldi.net/@ruario/113164179328218870
